# Generated by Django 3.2.4 on 2021-06-20 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_auto_20210619_0158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='album',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
